### PR TITLE
Feature/entity type input boolean

### PR DESCRIPTION
**Pull request by rforro**
I've added the `input_boolean` entity type (see #16) by myself. It was easier than I previously though. But one thing, I had to reuse your `switch_on/off.png` icons. I don't know where you got yours. If you don't like it, we can change them to `hass:check-circle` and `hass:circle-outline`.

### CODE REVIEW

**Comment by karlenek** [comment]
Great! I changed the the icon to a checkbox :)

**Comment by pystha** [comment]
Unfortunately if I add an input_boolean in the group, it will not show up.
I removed everything else from the group and now I get the message: "No entities configured"
This is the way to add input_booleans?

**Comment by rforro** [comment]
> 
> 
> Unfortunately if I add an input_boolean in the group, it will not show up.
> I removed everything else from the group and now I get the message: "No entities configured"
> This is the way to add input_booleans?

[input_boolean](https://www.home-assistant.io/integrations/input_boolean/) is an helper entity but is not different than any other. You can check following:

- you've created input_boolean as helper entity in HASS
- you've added it into your group mine is `input_boolean.away_mode`
- (if you run it in simulator, select `Reset All App Data`
- in widget menu run `Refresh entities`

**Comment by karlenek** [comment]
@pystha, not sure if you are referring to the version released or if you have cloned master branch and built it for your watch. This feature has not been released yet, so it won’t work if you downloaded the app from garmin. Will published together with som other changes in a few days!

**Pull request merged**
